# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bbb360c602ac5cf5bd45a9de6266c54849c573cb7405ce4ab41c95088f5061958f6b126c1b77a557a686ec2db9e5b7b395ffa59bb7f7e3cd95c8d83a8b7e58d

test:
  secret_key_base: cd3009ad3def9f65813e5f1c5d6edd13dadfed4884794ef5c1755ceb42830c37ea1dccb8a7e93d2fbce0e0776f97550ac6021cb40e3e1b6e89c3ad2d4954130e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
